### PR TITLE
:awing: Add pom and .gitignore

### PR DESCRIPTION
**Pull request by fergalmonaghan**
Project now mvn installs out of the box

Guys please review the pom groupId, artifactId and version in particular. Once you are happy with some values in there, would it be ok to mvn deploy the built artifacts to the central Maven repo? It would make reusing this project a lot easier :)

### CODE REVIEW

**Comment by fergalmonaghan** [comment]
Awesome, thanks @ptnplanet ! Would it be ok if I mvn deploy the built artifacts to the central Maven repo? It would make reusing this project a lot easier :)

**Comment by ptnplanet** [comment]
Hi @fergalmonaghan! I am currently working on getting it into the JitPack Repository as it seems to be the most easiest and fastest solution.

**Comment by fergalmonaghan** [comment]
Ah that is cool! I had not heard of Jitpack before but just checked it out: nice solution :) Let me know if you would like any help. Please I would appreciate it if you could ping a note here if and when it's available via Jitpack

**Comment by ptnplanet** [comment]
Hi @fergalmonaghan. I have just created a [v1.0.3 release](https://github.com/ptnplanet/Java-Naive-Bayes-Classifier/releases/tag/v1.0.3) with your pull request and another one (pr#7 that fixed the RunnableExample). It is now available via Jitpack. I have also updated the README.md.

Just add

```xml
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
```

to your pom.xml. You can then add the dependency as follows:

```xml
<dependency>
  <groupId>com.github.ptnplanet</groupId>
  <artifactId>java-naive-bayes-classifier</artifactId>
  <version>1.0.3</version>
</dependency>
```

Just tested it here and it works fine. If you have any troubles, just let me know.

Thank you very much - adding maven support was long overdue.

**Comment by fergalmonaghan** [comment]
Excellent, thanks for the heads up! I will aim to have a go at reusing this library in a new project tonight :)

**Comment by fergalmonaghan** [comment]
Hey I just noticed that the dependency details you put in the Readme and in the email to me are not the same as those that Jitpack gives/are necessary for the dependency to work:
https://jitpack.io/#ptnplanet/Java-Naive-Bayes-Classifier/v1.0.3
```
	<dependency>
	    <groupId>com.github.ptnplanet</groupId>
	    <artifactId>Java-Naive-Bayes-Classifier</artifactId>
	    <version>v1.0.3</version>
	</dependency>
```
These are the details that actually worked for me: note you have put a "v" before the version number so this is necessary in the dependency snippet I use. I'm not sure if the different casing of the artifactId is important

As a minor note, I also realised that the scope of junit can probably be set to "test" so that junit is used for running your tests but does not get packaged up in the final jar artifact. When scope is omitted, Maven defaults to "compile" scope which will include junit in your jar artifact. You can just add this tag inside the junit dependency (a sibling of version, artifactId etc.):
`<scope>test</scope>`

**Comment by ptnplanet** [comment]
Hi @fergalmonaghan. Good catch! I had testet it with my maven setup here and encountered no issues. I can however imagine, that in some cases the dependency's version number has to exactly match the git tag which is `v1.0.3`. The same most probably also applies to the git repository's name that has to case-sensitive match. I have therefor renamed all the tags by removing the v-prefix, updated the pom.xml, and also issued a new release `1.0.4` ([link](https://github.com/ptnplanet/Java-Naive-Bayes-Classifier/releases/tag/1.0.4)) where the junit dependency's scope is set to `test`. Thank you very much. Much appreciated.

**Pull request merged**
